# Generated by Django 3.0 on 2020-01-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='moviesfollowed',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
