# Generated by Django 3.0 on 2020-01-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_totalreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereview',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
