# Generated by Django 3.0 on 2020-02-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
