# Generated by Django 3.0 on 2020-01-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_moviefollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
